-- Create a table to store leads
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  
  -- Contact Info
  first_name text,
  last_name text,
  email text,
  phone text,
  region text,
  commune text,
  
  -- Vehicle Info
  plate text,
  make text,
  model text,
  year text,
  version text,
  mileage text,
  
  -- Valuation Data
  market_price numeric,
  immediate_offer numeric,
  consignment_price numeric,
  
  -- Metadata
  status text default 'new',
  notes text
);

-- Enable RLS
alter table public.leads enable row level security;

-- Allow insert for all (public form)
create policy "Allow public inserts" on public.leads
  for insert
  with check (true);

-- Allow select only for authenticated (service role or specific users)
create policy "Allow select for auth" on public.leads
  for select
  using (auth.role() = 'service_role');
